package gwat

import (
	"errors"
)

type clipData struct {
	Data []Clip `json:"data"`
}

// Clip represent a clip as described by the twitch API documentation.
type Clip struct {
	ID            string `json:"id"`
	URL           string `json:"url"`
	EmbedURL      string `json:"embed_url"`
	BroadcasterID string `json:"broadcaster_id"`
	CreatorID     string `json:"creator_id"`
	VideoID       string `json:"video_id"`
	GameID        string `json:"game_id"`
	Language      string `json:"language"`
	Title         string `json:"title"`
	ViewCount     int    `json:"view_count"`
	CreatedAt     string `json:"created_at"`
	ThumbnailURL  string `json:"thumbnail_url"`
}

type clipInfoData struct {
	Data []ClipInfo `json:"data"`
}

// DataClip represent the response generated by CreateClip as described by the twitch API documentation.
type ClipInfo struct {
	ID      string `json:"id"`
	editURL string `json:"edit_url"`
}

// CreateClip creates a clip and returns the information associated to the new clip.
// CreateClip requires an authentication token (authTkn) with scope 'clips:edit
// and the id of the stream from which the clip will be made (broadcasterID).
func (c *Client) CreateClip(broadcasterID, authTkn string) ([]ClipInfo, error) {
	uri := BaseURL + ClipsEP

	if !isNil(broadcasterID) {
		uri += "?broadcaster_id=" + broadcasterID
	} else {
		return nil, errors.New("broadcasterID must be specified")
	}

	h := Header{}
	if !isNil(authTkn) {
		h.Field = "Authorization"
		h.Value = "Bearer " + authTkn
	} else {
		return nil, errors.New("An authorization token is needed")
	}

	res, err := c.request("POST", uri, h)
	if err != nil {
		return nil, err
	}

	defer res.Body.Close()

	retClipInfo := clipInfoData{}
	if err := parseResult(res, &retClipInfo); err != nil {
		return nil, err
	}
	return retClipInfo.Data, nil
}

// GetClip gets information about a clip specified by an optional id.
func (c *Client) GetClip(id string) ([]Clip, error) {
	uri := BaseURL + ClipsEP

	if !isNil(id) {
		uri += "?id=" + id
	}

	h := Header{
		Field: "Client-ID",
		Value: c.ClientID,
	}

	res, err := c.request("GET", uri, h)
	if err != nil {
		return nil, err
	}

	defer res.Body.Close()

	retClip := clipData{}
	if err := parseResult(res, &retClip); err != nil {
		return nil, err
	}

	return retClip.Data, nil
}
